name: Build Windows Setup

on: [ push ]

jobs:
  windows-setup:
    name: Build xSB2 Windows x64 Setup
    runs-on: windows-latest

    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Configure CMake
        env:
          VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
        run: |
          cmake --preset "windows-x64" -DCMAKE_INSTALL_PREFIX="${{ github.workspace }}/xsb2-install" -DPACKAGE_XSB_ASSETS=ON
          # Clean up vcpkg temp dirs to save space
          Remove-Item $Env:VCPKG_INSTALLATION_ROOT\buildtrees\ -Force -Recurse -ErrorAction Continue
          Remove-Item $Env:VCPKG_INSTALLATION_ROOT\downloads\ -Force -Recurse -ErrorAction Continue

      - name: Build Release
        run: cmake --build --preset "windows-x64-release" --target INSTALL

      - name: Create Setup
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: "cmake-build-windows-x64/inno-installer/xsb-installer.iss"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-x64-setup
          path: cmake-build-windows-x64/inno-installer/compiled/windows-install.exe
          compression-level: 0
